language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

services:
  - docker

install:
  - pip install --upgrade pip && pip install -r requirements/base.txt

jobs:
  include:
    - stage: test
      script: cd booking_service && python -m manage test
    - stage: build
      script: docker-compose up -d --build

stages:
  - test
  - build
