language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

services:
  - docker

before_install: pip install --upgrade pip

install: pip install -r requirements/base.txt

script: echo "STARTING TESTS"

jobs:
  include:
    - stage: test
      script: cd booking_service && python -m manage test
    - stage: build
      script: docker-compose up -d --build

stages:
  - test
  - build
