language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

services:
  - docker

install:
  - pip install --upgrade pip && pip install -r requirements/base.txt

script:
  - cd booking_service && python -m manage test

after_success:
  - docker-compose up -d --build
